language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libboost1.55-dev
before_install:
  - sudo apt-get -qq update
  - sudo apt-get build-dep -y csound
  - wget https://github.com/csound/csound/archive/6.07.0.tar.gz
  - tar -xzvf 6.07.0.tar.gz
  - mkdir csound
  - pushd csound && cmake ../6.07.0 && make -j6 && sudo make install && sudo ldconfig && popd
before_script:
  - npm install -g jasmine
